version: '3.1'
services:
  producer:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAPADDRESS: kafka:9092
      SPRING_PROFILES_ACTIVE: producer
      MESSAGE_TOPIC_NAME: spring-topic
  
  consumer_alfa:
    build: .
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAPADDRESS: kafka:9092
      SPRING_PROFILES_ACTIVE: consumer
      MESSAGE_TOPIC_NAME: spring-topic
      GROUP_ID: foo
  
  consumer_beta:
    build: .
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAPADDRESS: kafka:9092
      SPRING_PROFILES_ACTIVE: consumer
      MESSAGE_TOPIC_NAME: spring-topic
      GROUP_ID: bar

  zookeeper:
    image: zookeeper
    restart: always
    #ports:
    #  - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    #    ports:
    #  - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
